

import prisma from "@/lib/prisma";

import {
  AFFICHAGE_INFORMATION_CHANNELS,
  CITIES,
  COUNTRIES,
  EVALUATION_OPTIONS,
  LEGAL_ENTITIES,
  LITIGE_CAUSES,
  LITIGE_OUTCOMES,
  OPPOSITION_NATURES,
  PAYMENT_MODES,
  STAGES,
  USER_TYPES,
} from "../lib/descriptors";

async function main() {
  console.log("🌱 Starting database seeding...");

  // Clear existing descriptors
  console.log("Clearing existing descriptors...");
  await prisma.descriptor.deleteMany();

  // Combine all descriptors
  const allDescriptors = [
    ...PAYMENT_MODES,
    ...EVALUATION_OPTIONS,
    ...OPPOSITION_NATURES,
    ...LITIGE_CAUSES,
    ...LITIGE_OUTCOMES,
    ...USER_TYPES,
    ...LEGAL_ENTITIES,
    ...STAGES,
    ...AFFICHAGE_INFORMATION_CHANNELS,
    ...COUNTRIES,
    ...CITIES,
  ];

  console.log(`Creating ${allDescriptors.length} descriptors...`);

  // Create descriptors
  const result = await prisma.descriptor.createMany({
    data: allDescriptors,
    skipDuplicates: true,
  });

  console.log(`✅ Created ${result.count} descriptors`);

  // Verify counts by type
  const types = [
    "payment_mode",
    "evaluation",
    "opposition_nature",
    "litige_cause",
    "litige_outcome",
    "user_type",
    "legal_entity",
    "stage",
    "affichage_channel",
    "country",
    "city",
  ];

  console.log("\n📊 Descriptors by type:");
  for (const type of types) {
    const count = await prisma.descriptor.count({
      where: { type },
    });
    console.log(`  ${type}: ${count}`);
  }

  // Create dummy surveys
  console.log("\n🔄 Creating dummy survey data...");
  await prisma.survey.deleteMany(); // Clear existing surveys

  const dummySurveys = [
    {
      email: "user1@example.com",
      stageReached: "Dépôt de dossier",
      dossierId: "DOS-2024-001",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "50000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      globalSatisfaction: "4",
    },
    {
      email: "user2@example.com",
      stageReached: "Enquête foncière",
      dossierId: "DOS-2024-002",
      depositCity: "Lambaréné",
      regularizationCity: "Lambaréné",
      residenceCity: "Lambaréné",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "5",
      depotPaymentMode: "Virement bancaire",
      depotAmountPaid: "60000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "5",
      globalSatisfaction: "5",
    },
    {
      email: "user3@example.com",
      stageReached: "Avis d'affichage",
      dossierId: "DOS-2024-003",
      depositCity: "Mouila",
      regularizationCity: "Mouila",
      residenceCity: "Mouila",
      userType: "Personne morale",
      legalEntity: "Société",
      nationality: "Gabonaise",
      depotEvaluation: "3",
      depotPaymentMode: "Chèque",
      depotAmountPaid: "75000",
      depotHasReceipt: true,
      depotHasAcknowledgment: false,
      enqueteDelayPerceived: "3-6 mois",
      enquetePaymentMode: "Mobile Money",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "Téléphone",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageFees: "25000",
      affichageHasReceipt: true,
      affichageSatisfaction: "4",
      globalSatisfaction: "4",
    },
    {
      email: "user4@example.com",
      stageReached: "PV et plan de bornage",
      dossierId: "DOS-2024-004",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "55000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "Email",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "5",
      bornageDelayPerceived: "2-3 mois",
      bornagePaymentMode: "Virement bancaire",
      bornageHasReceipt: true,
      bornageSatisfaction: "5",
      globalSatisfaction: "5",
    },
    {
      email: "user5@example.com",
      stageReached: "Rapport d'évaluation",
      dossierId: "DOS-2024-005",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "5",
      depotPaymentMode: "Virement bancaire",
      depotAmountPaid: "70000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Mobile Money",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "5",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "SMS",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "5",
      bornageDelayPerceived: "1-2 mois",
      bornagePaymentMode: "Espèces",
      bornageHasReceipt: true,
      bornageSatisfaction: "5",
      evaluationPriceUnderstanding: true,
      evaluationPaymentMode: "Virement bancaire",
      evaluationHasReceipt: true,
      evaluationSatisfaction: "5",
      globalSatisfaction: "5",
    },
    {
      email: "user6@example.com",
      stageReached: "Décision",
      dossierId: "DOS-2024-006",
      depositCity: "Lambaréné",
      regularizationCity: "Lambaréné",
      residenceCity: "Lambaréné",
      userType: "Personne morale",
      legalEntity: "Société",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Chèque",
      depotAmountPaid: "80000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "3-6 mois",
      enquetePaymentMode: "Chèque",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      affichageInTime: false,
      affichageWasInformed: true,
      affichageInformationChannel: "Courrier",
      affichageSufficientDelay: false,
      affichageHasOpposition: true,
      affichageSatisfaction: "3",
      bornageDelayPerceived: "3-6 mois",
      bornagePaymentMode: "Virement bancaire",
      bornageHasReceipt: true,
      bornageSatisfaction: "3",
      evaluationPriceUnderstanding: true,
      evaluationPaymentMode: "Virement bancaire",
      evaluationHasReceipt: true,
      evaluationSatisfaction: "4",
      decisionDelay: "6-12 mois",
      decisionPaymentMode: "Virement bancaire",
      decisionHasReceipt: true,
      wasTransmitted: true,
      hasActeCession: true,
      hasTitrePropriete: false,
      decisionSatisfaction: "4",
      globalSatisfaction: "4",
    },
    {
      email: "user7@example.com",
      stageReached: "Dépôt de dossier",
      dossierId: "DOS-2024-007",
      depositCity: "Mouila",
      regularizationCity: "Mouila",
      residenceCity: "Mouila",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "2",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "45000",
      depotHasReceipt: false,
      depotHasAcknowledgment: false,
      globalSatisfaction: "2",
    },
    {
      email: "user8@example.com",
      stageReached: "Enquête foncière",
      dossierId: "DOS-2024-008",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "3",
      depotPaymentMode: "Mobile Money",
      depotAmountPaid: "52000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "Plus de 12 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: false,
      enqueteSatisfaction: "2",
      globalSatisfaction: "2",
    },
    {
      email: "user9@example.com",
      stageReached: "Avis d'affichage",
      dossierId: "DOS-2024-009",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne morale",
      legalEntity: "Association",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Virement bancaire",
      depotAmountPaid: "65000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "3-6 mois",
      enquetePaymentMode: "Virement bancaire",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "En personne",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "4",
      globalSatisfaction: "4",
    },
    {
      email: "user10@example.com",
      stageReached: "PV et plan de bornage",
      dossierId: "DOS-2024-010",
      depositCity: "Lambaréné",
      regularizationCity: "Lambaréné",
      residenceCity: "Lambaréné",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "5",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "58000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "5",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "Téléphone",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "5",
      bornageDelayPerceived: "1-2 mois",
      bornagePaymentMode: "Mobile Money",
      bornageHasReceipt: true,
      bornageSatisfaction: "5",
      globalSatisfaction: "5",
    },
    {
      email: "user11@example.com",
      stageReached: "Rapport d'évaluation",
      dossierId: "DOS-2024-011",
      depositCity: "Mouila",
      regularizationCity: "Mouila",
      residenceCity: "Mouila",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "3",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "48000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "6-12 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "3",
      affichageInTime: false,
      affichageWasInformed: false,
      affichageSufficientDelay: false,
      affichageHasOpposition: true,
      affichageSatisfaction: "2",
      bornageDelayPerceived: "6-12 mois",
      bornagePaymentMode: "Espèces",
      bornageHasReceipt: true,
      bornageSatisfaction: "3",
      evaluationPriceUnderstanding: false,
      evaluationPaymentMode: "Espèces",
      evaluationHasReceipt: true,
      evaluationSatisfaction: "3",
      globalSatisfaction: "3",
    },
    {
      email: "user12@example.com",
      stageReached: "Décision",
      dossierId: "DOS-2024-012",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "5",
      depotPaymentMode: "Virement bancaire",
      depotAmountPaid: "72000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Virement bancaire",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "5",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "Email",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "5",
      bornageDelayPerceived: "1-2 mois",
      bornagePaymentMode: "Virement bancaire",
      bornageHasReceipt: true,
      bornageSatisfaction: "5",
      evaluationPriceUnderstanding: true,
      evaluationPaymentMode: "Virement bancaire",
      evaluationHasReceipt: true,
      evaluationSatisfaction: "5",
      decisionDelay: "3-6 mois",
      decisionPaymentMode: "Virement bancaire",
      decisionHasReceipt: true,
      wasTransmitted: true,
      hasActeCession: true,
      hasTitrePropriete: true,
      decisionSatisfaction: "5",
      globalSatisfaction: "5",
    },
    {
      email: "user13@example.com",
      stageReached: "Dépôt de dossier",
      dossierId: "DOS-2024-013",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Mobile Money",
      depotAmountPaid: "53000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      globalSatisfaction: "4",
    },
    {
      email: "user14@example.com",
      stageReached: "Enquête foncière",
      dossierId: "DOS-2024-014",
      depositCity: "Lambaréné",
      regularizationCity: "Lambaréné",
      residenceCity: "Lambaréné",
      userType: "Personne morale",
      legalEntity: "Société",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Chèque",
      depotAmountPaid: "78000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "3-6 mois",
      enquetePaymentMode: "Chèque",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      globalSatisfaction: "4",
    },
    {
      email: "user15@example.com",
      stageReached: "Avis d'affichage",
      dossierId: "DOS-2024-015",
      depositCity: "Mouila",
      regularizationCity: "Mouila",
      residenceCity: "Mouila",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "3",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "49000",
      depotHasReceipt: true,
      depotHasAcknowledgment: false,
      enqueteDelayPerceived: "6-12 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: false,
      enqueteSatisfaction: "3",
      affichageInTime: false,
      affichageWasInformed: true,
      affichageInformationChannel: "Téléphone",
      affichageSufficientDelay: false,
      affichageHasOpposition: false,
      affichageSatisfaction: "3",
      globalSatisfaction: "3",
    },
    {
      email: "user16@example.com",
      stageReached: "PV et plan de bornage",
      dossierId: "DOS-2024-016",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "56000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "SMS",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "4",
      bornageDelayPerceived: "2-3 mois",
      bornagePaymentMode: "Mobile Money",
      bornageHasReceipt: true,
      bornageSatisfaction: "4",
      globalSatisfaction: "4",
    },
    {
      email: "user17@example.com",
      stageReached: "Rapport d'évaluation",
      dossierId: "DOS-2024-017",
      depositCity: "Lambaréné",
      regularizationCity: "Lambaréné",
      residenceCity: "Lambaréné",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "5",
      depotPaymentMode: "Virement bancaire",
      depotAmountPaid: "68000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Virement bancaire",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "5",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "Email",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "5",
      bornageDelayPerceived: "1-2 mois",
      bornagePaymentMode: "Virement bancaire",
      bornageHasReceipt: true,
      bornageSatisfaction: "5",
      evaluationPriceUnderstanding: true,
      evaluationPaymentMode: "Virement bancaire",
      evaluationHasReceipt: true,
      evaluationSatisfaction: "5",
      globalSatisfaction: "5",
    },
    {
      email: "user18@example.com",
      stageReached: "Décision",
      dossierId: "DOS-2024-018",
      depositCity: "Mouila",
      regularizationCity: "Mouila",
      residenceCity: "Mouila",
      userType: "Personne morale",
      legalEntity: "Société",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Chèque",
      depotAmountPaid: "85000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "3-6 mois",
      enquetePaymentMode: "Chèque",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      affichageInTime: true,
      affichageWasInformed: true,
      affichageInformationChannel: "Courrier",
      affichageSufficientDelay: true,
      affichageHasOpposition: false,
      affichageSatisfaction: "4",
      bornageDelayPerceived: "3-6 mois",
      bornagePaymentMode: "Chèque",
      bornageHasReceipt: true,
      bornageSatisfaction: "4",
      evaluationPriceUnderstanding: true,
      evaluationPaymentMode: "Chèque",
      evaluationHasReceipt: true,
      evaluationSatisfaction: "4",
      decisionDelay: "6-12 mois",
      decisionPaymentMode: "Chèque",
      decisionHasReceipt: true,
      wasTransmitted: true,
      hasActeCession: true,
      hasTitrePropriete: false,
      decisionSatisfaction: "4",
      globalSatisfaction: "4",
    },
    {
      email: "user19@example.com",
      stageReached: "Dépôt de dossier",
      dossierId: "DOS-2024-019",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "5",
      depotPaymentMode: "Mobile Money",
      depotAmountPaid: "54000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      globalSatisfaction: "5",
    },
    {
      email: "user20@example.com",
      stageReached: "Enquête foncière",
      dossierId: "DOS-2024-020",
      depositCity: "Libreville",
      regularizationCity: "Libreville",
      residenceCity: "Libreville",
      userType: "Personne physique",
      legalEntity: "Personne physique",
      nationality: "Gabonaise",
      depotEvaluation: "4",
      depotPaymentMode: "Espèces",
      depotAmountPaid: "51000",
      depotHasReceipt: true,
      depotHasAcknowledgment: true,
      enqueteDelayPerceived: "1-2 mois",
      enquetePaymentMode: "Espèces",
      enqueteHasReceipt: true,
      enqueteSatisfaction: "4",
      globalSatisfaction: "4",
    },
  ];

  for (const survey of dummySurveys) {
    await prisma.survey.create({
      data: survey,
    });
  }

  console.log(`✅ Created ${dummySurveys.length} dummy surveys`);

  // Verify survey distribution
  console.log("\n📊 Surveys by city:");
  for (const city of ["Libreville", "Lambaréné", "Mouila"]) {
    const count = await prisma.survey.count({
      where: { depositCity: city },
    });
    console.log(`  ${city}: ${count}`);
  }

  console.log("\n📊 Surveys by stage:");
  const stages = [
    "Dépôt de dossier",
    "Enquête foncière",
    "Avis d'affichage",
    "PV et plan de bornage",
    "Rapport d'évaluation",
    "Décision",
  ];
  for (const stage of stages) {
    const count = await prisma.survey.count({
      where: { stageReached: stage },
    });
    console.log(`  ${stage}: ${count}`);
  }

  console.log("\n✨ Database seeding completed successfully!");
}

main()
  .catch((error) => {
    console.error("❌ Error during seeding:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
